# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feedback.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x65\x64\x62\x61\x63k.proto\"v\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12-\n\x10sentenceFeedback\x18\x01 \x01(\x0b\x32\x11.SentenceFeedbackH\x00\x12/\n\x11timetableFeedback\x18\x02 \x01(\x0b\x32\x12.TimetableFeedbackH\x00\x42\n\n\x08\x66\x65\x65\x64\x62\x61\x63k\"#\n\x10SentenceFeedback\x12\x0f\n\x07message\x18\x01 \x01(\t\"]\n\x11TimetableFeedback\x12\x14\n\x0c\x66rom_station\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x01(\t\x12#\n\ndepartures\x18\x03 \x03(\x0b\x32\x0f.DepartureEntry\"k\n\x0e\x44\x65partureEntry\x12\x15\n\rdepartureTime\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x0c\n\x04line\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDBACK']._serialized_start=18
  _globals['_FEEDBACK']._serialized_end=136
  _globals['_SENTENCEFEEDBACK']._serialized_start=138
  _globals['_SENTENCEFEEDBACK']._serialized_end=173
  _globals['_TIMETABLEFEEDBACK']._serialized_start=175
  _globals['_TIMETABLEFEEDBACK']._serialized_end=268
  _globals['_DEPARTUREENTRY']._serialized_start=270
  _globals['_DEPARTUREENTRY']._serialized_end=377
# @@protoc_insertion_point(module_scope)
