# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mainService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mainService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import userInput_pb2 as userInput__pb2
import feedback_pb2 as feedback__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mainService.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0fuserInput.proto\x1a\x0e\x66\x65\x65\x64\x62\x61\x63k.proto2x\n\x11TravelChatService\x12-\n\tsendInput\x12\n.UserInput\x1a\x12.UserInputResponse\"\x00\x12\x34\n\x0bgetFeedback\x12\x16.google.protobuf.Empty\x1a\t.Feedback\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mainService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAVELCHATSERVICE']._serialized_start=83
  _globals['_TRAVELCHATSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
