# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import feedback_pb2 as feedback__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import userInput_pb2 as userInput__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mainService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TravelChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendInput = channel.unary_unary(
                '/TravelChatService/sendInput',
                request_serializer=userInput__pb2.UserInput.SerializeToString,
                response_deserializer=userInput__pb2.UserInputResponse.FromString,
                _registered_method=True)
        self.getFeedback = channel.unary_stream(
                '/TravelChatService/getFeedback',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=feedback__pb2.Feedback.FromString,
                _registered_method=True)


class TravelChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TravelChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendInput': grpc.unary_unary_rpc_method_handler(
                    servicer.sendInput,
                    request_deserializer=userInput__pb2.UserInput.FromString,
                    response_serializer=userInput__pb2.UserInputResponse.SerializeToString,
            ),
            'getFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.getFeedback,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=feedback__pb2.Feedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TravelChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TravelChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TravelChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TravelChatService/sendInput',
            userInput__pb2.UserInput.SerializeToString,
            userInput__pb2.UserInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/TravelChatService/getFeedback',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            feedback__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
