# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: userInput.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'userInput.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuserInput.proto\"\\\n\tUserInput\x12#\n\x0bstringInput\x18\x01 \x01(\x0b\x32\x0c.StringInputH\x00\x12!\n\naudioInput\x18\x02 \x01(\x0b\x32\x0b.AudioInputH\x00\x42\x07\n\x05input\"$\n\x11UserInputResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\x0bStringInput\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nAudioInput\x12\r\n\x05value\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userInput_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINPUT']._serialized_start=19
  _globals['_USERINPUT']._serialized_end=111
  _globals['_USERINPUTRESPONSE']._serialized_start=113
  _globals['_USERINPUTRESPONSE']._serialized_end=149
  _globals['_STRINGINPUT']._serialized_start=151
  _globals['_STRINGINPUT']._serialized_end=179
  _globals['_AUDIOINPUT']._serialized_start=181
  _globals['_AUDIOINPUT']._serialized_end=208
# @@protoc_insertion_point(module_scope)
